version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app:rw
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for ibeam container management
    command: gunicorn -w 4 -b 0.0.0.0:8080 wsgi:app
